##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.17.1] date: [Mon Jul 11 22:45:14 CST 2022]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = motorcontrol
HOST_CC ?= cc

# Safe by default. Set SAFE_BRINGUP=0 only after the Phase-0 hardware and safety
# gates in docs/PROJECT_PLAN.md have passed and the resulting diff is reviewed.
SAFE_BRINGUP ?= 1
# Low-current single-phase injection bring-up. Implies SAFE_BRINGUP=0 but adds
# its own gated profile, banner, symbol audit and fixed limits.
BRINGUP_INJECT ?= 0
# CAN-only path probe: leaves SAFE_BRINGUP protections enabled and bypasses
# diagnostic CRC parsing to prove the RX interrupt and TX path independently.
CAN_PROBE ?= 0

ifeq ($(BRINGUP_INJECT), 1)
override SAFE_BRINGUP := 0
override BUILD_PROFILE := inject
else ifeq ($(SAFE_BRINGUP), 1)
override BUILD_PROFILE := safe
else
override BUILD_PROFILE := unsafe
endif


######################################
# building variables
######################################
# debug build?
# DEBUG = 1
# optimization
# OPT = -Og
OPT = -O2
OPT += -fsingle-precision-constant


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build
override OUTPUT_DIR := $(BUILD_DIR)/$(BUILD_PROFILE)

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/safety.c \
Core/Src/gpio.c \
Core/Src/adc.c \
Core/Src/can.c \
Core/Src/config_store.c \
Core/Src/normal_can_protocol.c \
Core/Src/as5047_protocol.c \
Core/Src/diag_protocol.c \
Core/Src/diagnostics.c \
Core/Src/spi.c \
Core/Src/tim.c \
Core/Src/usart.c \
Core/Src/calibration.c \
Core/Src/drv8323.c \
Core/Src/flash_writer.c \
Core/Src/foc.c \
Core/Src/fsm.c \
Core/Src/math_ops.c \
Core/Src/position_sensor.c \
Core/Src/preference_writer.c \
Core/Src/motor_gate.c \
Core/Src/syscalls.c \
Core/Src/sysmem.c \
Core/Src/systick.c \
Core/Src/gd32f30x_it.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_adc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_bkp.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_can.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_crc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_ctc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_dac.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_dbg.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_dma.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_enet.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_exmc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_exti.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_fmc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_fwdgt.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_gpio.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_i2c.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_misc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_pmu.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_rcu.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_rtc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_sdio.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_spi.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_timer.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_usart.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_wwdgt.c \
Firmware/CMSIS/GD/GD32F30x/Source/system_gd32f30x.c

ifeq ($(BRINGUP_INJECT), 1)
C_SOURCES += Core/Src/inject.c
endif

# ASM sources
ASM_SOURCES =  \
startup_gd32f30x_hd.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
NM = $(patsubst %gcc,%nm,$(CC))
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DGD32F30X_HD

ifeq ($(SAFE_BRINGUP), 1)
C_DEFS += -DSAFE_BRINGUP=1
endif
ifeq ($(BRINGUP_INJECT), 1)
C_DEFS += -DBRINGUP_INJECT=1
endif
ifeq ($(CAN_PROBE), 1)
C_DEFS += -DCAN_PROBE=1
endif


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IFirmware/GD32F30x_standard_peripheral/Include \
-IFirmware/CMSIS/GD/GD32F30x/Include \
-IFirmware/CMSIS


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = GD32F303RETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(OUTPUT_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# printf support float, 6Kbytes
LDFLAGS += -u _printf_float

# default action: build all
all: $(OUTPUT_DIR)/$(TARGET).elf $(OUTPUT_DIR)/$(TARGET).hex $(OUTPUT_DIR)/$(TARGET).bin

ifeq ($(SAFE_BRINGUP), 1)
all: verify-safe
endif
ifeq ($(BRINGUP_INJECT), 1)
all: verify-inject
endif

host-test:
	$(HOST_CC) -std=c11 -Wall -Wextra -Werror -ICore/Inc \
		Core/Src/diag_protocol.c Core/Src/as5047_protocol.c \
		tests/diag_protocol_test.c tests/as5047_protocol_test.c \
		-o /tmp/athena_diag_protocol_test
	/tmp/athena_diag_protocol_test

host-inject-test:
	$(HOST_CC) -std=c11 -Wall -Wextra -Werror -DBRINGUP_INJECT=1 -ICore/Inc \
		Core/Src/diag_protocol.c tests/inject_protocol_test.c \
		-o /tmp/athena_inject_protocol_test
	/tmp/athena_inject_protocol_test

host-tools-test:
	$(MAKE) -C tools/athena_diag_uc12 test
	bash tools/athena_safe_flash.sh self-test

host-app-test:
	$(HOST_CC) -std=c11 -Wall -Wextra -Werror -ICore/Inc \
		Core/Src/motor_gate.c Core/Src/config_store.c Core/Src/normal_can_protocol.c \
		Core/Src/diag_protocol.c \
		tests/motor_gate_test.c tests/config_store_test.c tests/normal_can_protocol_test.c \
		-o /tmp/athena_motor_gate_test
	/tmp/athena_motor_gate_test

host-mit-test:
	PYTHONPATH=. python3 -m unittest -v tests/mit_codec_test.py

verify-normal: $(OUTPUT_DIR)/$(TARGET).elf
	sh tools/verify_normal_image.sh $(NM) $<

verify-safe: $(OUTPUT_DIR)/$(TARGET).elf
	sh tools/verify_safe_image.sh $(NM) $<

verify-inject: $(OUTPUT_DIR)/$(TARGET).elf
	sh tools/verify_inject_image.sh $(NM) $<

.PHONY: all host-test host-inject-test host-tools-test host-app-test verify-safe verify-inject verify-normal clean


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(OUTPUT_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(OUTPUT_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(OUTPUT_DIR)/%.o: %.c Makefile | $(OUTPUT_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(OUTPUT_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(OUTPUT_DIR)/%.o: %.s Makefile | $(OUTPUT_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(OUTPUT_DIR)/$(TARGET).elf: $(OBJECTS) Makefile tools/verify_safe_image.sh
ifeq ($(BRINGUP_INJECT), 1)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@.unverified
	$(SZ) $@.unverified
	@if ! sh tools/verify_inject_image.sh $(NM) $@.unverified; then \
		rm -f $@.unverified; \
		exit 1; \
	fi
	mv $@.unverified $@
else ifeq ($(SAFE_BRINGUP), 1)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@.unverified
	$(SZ) $@.unverified
	@if ! sh tools/verify_safe_image.sh $(NM) $@.unverified; then \
		rm -f $@.unverified; \
		exit 1; \
	fi
	mv $@.unverified $@
else
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@
endif

$(OUTPUT_DIR)/%.hex: $(OUTPUT_DIR)/%.elf | $(OUTPUT_DIR)
	$(HEX) $< $@
	
$(OUTPUT_DIR)/%.bin: $(OUTPUT_DIR)/%.elf | $(OUTPUT_DIR)
	$(BIN) $< $@	
	
$(OUTPUT_DIR):
	mkdir -p $@

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(OUTPUT_DIR)/*.d)

# *** EOF ***
