##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.17.1] date: [Mon Jul 11 22:45:14 CST 2022]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = motorcontrol

# Safe by default. Set SAFE_BRINGUP=0 only after the Phase-0 hardware and safety
# gates in docs/PROJECT_PLAN.md have passed and the resulting diff is reviewed.
SAFE_BRINGUP ?= 1


######################################
# building variables
######################################
# debug build?
# DEBUG = 1
# optimization
# OPT = -Og
OPT = -O2
OPT += -fsingle-precision-constant


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/safety.c \
Core/Src/gpio.c \
Core/Src/adc.c \
Core/Src/can.c \
Core/Src/spi.c \
Core/Src/tim.c \
Core/Src/usart.c \
Core/Src/calibration.c \
Core/Src/drv8323.c \
Core/Src/flash_writer.c \
Core/Src/foc.c \
Core/Src/fsm.c \
Core/Src/math_ops.c \
Core/Src/position_sensor.c \
Core/Src/preference_writer.c \
Core/Src/syscalls.c \
Core/Src/sysmem.c \
Core/Src/systick.c \
Core/Src/gd32f30x_it.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_adc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_bkp.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_can.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_crc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_ctc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_dac.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_dbg.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_dma.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_enet.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_exmc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_exti.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_fmc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_fwdgt.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_gpio.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_i2c.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_misc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_pmu.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_rcu.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_rtc.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_sdio.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_spi.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_timer.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_usart.c \
Firmware/GD32F30x_standard_peripheral/Source/gd32f30x_wwdgt.c \
Firmware/CMSIS/GD/GD32F30x/Source/system_gd32f30x.c

# ASM sources
ASM_SOURCES =  \
startup_gd32f30x_hd.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DGD32F30X_HD

ifeq ($(SAFE_BRINGUP), 1)
C_DEFS += -DSAFE_BRINGUP=1
endif


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IFirmware/GD32F30x_standard_peripheral/Include \
-IFirmware/CMSIS/GD/GD32F30x/Include \
-IFirmware/CMSIS


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = GD32F303RETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# printf support float, 6Kbytes
LDFLAGS += -u _printf_float

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
